id: A571B704A
title: f1242
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 14:45:54.212221
  last_modified_at: 2022-05-27 14:45:54.212226
