id: A571B704A
title: fC6C2
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 14:45:54.531980
  last_modified_at: 2022-05-27 14:45:54.531983
