id: A571B704A
title: fA2F7
type: translation
source_metadata:
  languages:
  - en
  - bo
  - zh
  - pgd
  - sa
  datatype: PlainText
  created_at: 2022-05-27 14:45:54.416274
  last_modified_at: 2022-05-27 14:45:54.416277
